/* Auto-generated by tools/gen-audio.js — do not edit by hand. */
window.HANATALK_AUDIO = {"안녕하세요":"audio/0001.mp3","감사합니다":"audio/0002.mp3","죄송합니다":"audio/0003.mp3","괜찮아요":"audio/0004.mp3","이거 얼마예요?":"audio/0005.mp3","카드 되나요?":"audio/0006.mp3","메뉴판 주세요":"audio/0007.mp3","여기서 내려주세요":"audio/0008.mp3","지하철역이 어디예요?":"audio/0009.mp3","병원에 가야 해요":"audio/0010.mp3","도와주세요":"audio/0011.mp3"};
