#!/usr/bin/env node
'use strict';
const fs = require('fs');
const path = require('path');
const { execFileSync } = require('child_process');

const ROOT = path.resolve(__dirname, '..');
const AUDIO_DIR = path.join(ROOT, 'audio');
const GOOGLE = (s) => 'https://translate.google.com/translate_tts?ie=UTF-8&tl=ko&client=tw-ob&q=' + encodeURIComponent(s);

const dataSrc = fs.readFileSync(path.join(ROOT, 'data.js'), 'utf8');
const HanaTalkData = new Function(dataSrc + '\n;return HanaTalkData;')();

const strings = [];
const seen = new Set();
HanaTalkData.ENTRIES.forEach(e => { if (!seen.has(e.ko)) { seen.add(e.ko); strings.push(e.ko); } });

function sleep(ms) { Atomics.wait(new Int32Array(new SharedArrayBuffer(4)), 0, 0, ms); }

function isValidMp3(file) {
  let b;
  try { b = fs.readFileSync(file); } catch (e) { return false; }
  if (b.length < 800) return false;
  return (b[0] === 0x49 && b[1] === 0x44 && b[2] === 0x33) || (b[0] === 0xFF && (b[1] & 0xE0) === 0xE0);
}

function fetchMp3(url, outFile) {
  for (let attempt = 0; attempt < 4; attempt++) {
    try {
      execFileSync('curl', ['-fsSL', '--max-time', '20', '-A', 'Mozilla/5.0', url, '-o', outFile], { stdio: 'ignore' });
      if (isValidMp3(outFile)) return true;
    } catch (e) { /* retry */ }
    sleep(600 + attempt * 600);
  }
  try { fs.existsSync(outFile) && fs.unlinkSync(outFile); } catch (e) {}
  return false;
}

fs.mkdirSync(AUDIO_DIR, { recursive: true });
for (const f of fs.readdirSync(AUDIO_DIR)) {
  if (/\.mp3$/i.test(f)) fs.unlinkSync(path.join(AUDIO_DIR, f));
}

const map = {};
let failed = 0;
const failedStrings = [];
strings.forEach((s, i) => {
  const id = String(i + 1).padStart(4, '0');
  const outFile = path.join(AUDIO_DIR, id + '.mp3');
  if (fetchMp3(GOOGLE(s), outFile)) {
    map[s] = 'audio/' + id + '.mp3';
  } else {
    failed++;
    failedStrings.push(s);
  }
  sleep(250);
  process.stdout.write(`\r[${i + 1}/${strings.length}] ${s}            `);
});
process.stdout.write('\n');

fs.writeFileSync(
  path.join(AUDIO_DIR, 'manifest.js'),
  '/* Auto-generated by tools/gen-audio.js — do not edit by hand. */\nwindow.HANATALK_AUDIO = ' + JSON.stringify(map) + ';\n'
);

console.log(`Done. ${Object.keys(map).length}/${strings.length} clips generated, ${failed} failed.`);
if (failedStrings.length) console.log('Failed (will use Web Speech fallback at runtime): ' + failedStrings.join(' '));
